@startuml network

nwdiag {
    network bridge {
        address = "0.0.0.0/0";
        nginx [address = "localhost:80"];
        adminer [address = "localhost:8080"];
    }
    network front-end {
        address = "";
        nginx [address = ""];
        ws [address = "ws:5000"];
        php-fpm [address = "php-fpm:9000"];
    }
    network back-end {
        address = "";
        php-fpm [address = ""];
        adminer [address = ""];
        db [address = "db:3306"];
    }
}

@enduml