DROP TABLE IF EXISTS books;
CREATE TABLE books (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    author VARCHAR(256),
    publisher VARCHAR(256),
    isbn VARCHAR(16),
    price INTEGER,
    url VARCHAR(256)
    -- delete_flag BOOLEAN NOT NULL DEFAULT FALSE,
    -- created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(32) NOT NULL
);